crate-ci/typos

src/main.rs
=> Control over what files are ignored

Cargo.lock, Cargo.toml, benches/file.rs, src/lib.rs, src/main.rs
=>  feat: Ignore binary files 

benches/file.rs, benches/tokenize.rs, docs/about.md, src/lib.rs, src/main.rs, src/report.rs, src/tokens.rs
=>  feat: Check file names

Cargo.lock, Cargo.toml, src/main.rs
=> feat: Log debug information

Cargo.lock, Cargo.toml, src/checks.rs, src/config.rs, src/lib.rs, src/main.rs, src/report.rs, src/tokens.rs
=> Config file support

Cargo.toml, benchsuite/benchsuite.sh, benchsuite/fixtures/linux_built.sh, benchsuite/fixtures/linux_clean.sh, benchsuite/fixtures/ripgrep_built.sh, benchsuite/fixtures/ripgrep_clean.sh, benchsuite/fixtures/subtitles_en.sh, benchsuite/fixtures/subtitles_en_small.sh, benchsuite/fixtures/subtitles_ru.sh, benchsuite/fixtures/subtitles_ru_small.sh, benchsuite/runs/2019-10-24-Nightblood.md, benchsuite/uut/codespell.sh, benchsuite/uut/misspell_go.sh, benchsuite/uut/misspell_rs.sh, benchsuite/uut/rg.sh, benchsuite/uut/scspell.sh, benchsuite/uut/typos.sh
=>  perf: Benchmark 0.1 

Cargo.lock, Cargo.toml, benches/file.rs, benches/tokenize.rs, typos/src/checks.rs
- More benchmarks
- Resolve issues that didn't actually help (much)
=> Look into processing overhead

benchsuite/benchsuite.sh, src/main.rs, typos/src/dict.rs, typos/src/report.rs
BREAKING CHANGE: `trait typos::Dictionary` now requires `Send + Sync`.
=> Refactor to prepare for errors

benches/file.rs, src/main.rs, typos/src/checks.rs, typos/src/report.rs, typos/src/tokens.rs
This will help people debug their configurations.
Fixes #41
=> feat: Dump files, identifiers, and words

Cargo.lock, azure-pipelines.yml, benchsuite/benchsuite.sh, src/main.rs
=> perf: Multi-threaded spell checking 

src/main.rs, typos/src/checks.rs, typos/src/report.rs
=> Refactor in prep for correction support

crates/typos/src/checks.rs, crates/typos/src/dict.rs, crates/typos/src/report.rs, src/dict.rs, src/replace.rs
Some of the other spell checkers already do this. While I've not checked
where we might need it for our dictionary, this will be important for
dialects.
=> feat: Support multiple, valid corrections

crates/typos/src/report.rs
- We aren't consistent in quoting words
- We used byte offsets rather than column counts
- We mixed styles between disallowed and corrections
Fixes #165
=> fix(report): Rendering issues with errors

src/checks.rs, src/main.rs
This helps with tool integration.
Fixes #195
=> feat: Support '-' for stdin

src/args.rs, src/config.rs, src/main.rs
This focuses on how the command line can help document features in a more living way than the markdown files.
=> Improve feature discoverability

Cargo.lock, Cargo.toml, azure-pipelines.yml, src/config.rs, src/dict.rs
The obvious case is building for docs.rs but this can be helpful for
special use cases or faster development iteration.
=> chore(cli): Allow building without expensive parts

crates/typos-dict/verify/src/main.rs, src/dict.rs
We had a bug where `finallizes` with EnGb would not correct to
`finalises`
=> fix(dict): Correctly connect dict with varcon 

CHANGELOG.md, Cargo.lock, Cargo.toml, src/file.rs
=> fix(cli): Don't crash on stdin

src/bin/typos-cli/args.rs
=> docs(cli): Clarify help string for 'exclude'

CHANGELOG.md, src/bin/typos-cli/main.rs, tests/cli.rs
=> fix(cli): Don't panic

CHANGELOG.md, crates/typos-dict/assets/words.csv
=> fix(dict): Avoid contraction false positive

Cargo.lock, Cargo.toml
=> chore: Remove 'difference' dependency

src/config.rs, src/policy.rs
=> fix(config): Skip checking cert contents 

crates/typos/src/tokens.rs
Just ignoring them since our focus is on programmer typos and these
can't be identifiers.  This is simpler and is less work at runtime.
Fixes #331
=> fix: Reduce false positives from ordinals

crates/typos/src/dict.rs, crates/typos/src/tokens.rs
Unfortunately, almost all of this is for corrections.
=> perf: Remove some function overhead

crates/typos-dict/assets/words.csv
I encountered these when going through a codebase with another tool.
=> feat(dict): Add more corrections

crates/typos-dict/assets/words.csv
Found this in the clap code base.
=> fix: Detect descrepancy

setup.py
Borrowed from https://github.com/shellcheck-py/shellcheck-py/pull/42, thanks to @DragonCrafted87.
I have no idea if this actually works nor do I have an easy way to check, just happened to notice and thought it might.
=> feat(pre-commit): Make work on cygwin

crates/typos-dict/assets/words.csv
=> fix(dict): Workes should also correct to workers

crates/typos/src/tokens.rs
=> fix(parser): Allow markdown formatting around ordinals

crates/typos/src/tokens.rs
This is part of the way to #413.  In that case, they aren't providing
padding though.
=> fix(parser): Detect shorter base64 values

crates/typos/src/tokens.rs
Got us closer to https://www.ietf.org/rfc/rfc3986.txt
Fixes https://github.com/crate-ci/typos/issues/433
=> fix(parser): Allow commas in urls 

crates/typos/src/tokens.rs
=> fix: Ignore CSS colors

CONTRIBUTING.md, crates/typos-dict/assets/words.csv
- signign -> signing
- unencyrpted -> unencrypted
This supersedes #467
=> Add a couple of typos

src/bin/typos-cli/report.rs
Sorry for the inconvenience.
I found that `unic_emoji_char::is_emoji` classifies `0`..`9` as emoji leading to misalignments.
=> fix: Fix miscalculating the width of numbers and some symbols

.github/workflows/test-action.yml, .pre-commit-config.yaml, docker/Dockerfile, docker/entrypoint.sh
Inspired by a snippet from @arminrosu on #429.
Fixes #429
=> feat(action): Report typos as annotations

src/bin/typos-cli/main.rs
=> fix(cli): Skip files that stdout is writing to

docker/Dockerfile, docker/entrypoint.sh, docker/format_gh.sh
=> fix(gh): Don't report bad annotations for binary files

crates/typos-dict/assets/words.csv
I added new typos by using [GitHub Typo Corpus](https://github.com/mhagiwara/github-typo-corpus).
The code to find typos is [shirayu/find_new_typos](https://github.com/shirayu/find_new_typos).
(You can set another parameters to find new typos.)
=> Add new typos

src/config.rs
=> fix(config): Ignore thead for jsx/tsx

crates/typos-dict/assets/words.csv
Not sure what to use for the PR title / commit message - is "assorted typo fixes" acceptable? Preferred?
(thanks for all the work you put into typos! it's fantastic 🤩)
=> feat(dict): add typos from Fig monorepo

crates/typos-dict/assets/words.csv, src/config.rs
=> fix: Never correct thead

crates/typos-dict/assets/words.csv
I added some typos by using my script ([shirayu/find_new_typos](https://github.com/shirayu/find_new_typos)).
=> Add some typos

README.md
Add Homebrew installation instructions
Resolves #598
=> docs: Add Homebrew installation instructions

src/bin/typos-cli/report.rs
Including not crashing.  Granted, for some reason I'm not seeing why the new code doesn't crash.
=> fix(cli): Have brief match long behavior

.pre-commit-hooks.yaml
https://pre-commit.com/#confining-hooks-to-run-at-certain-stages
=> feat(pre-commit): Improve (/limit) default set of stages to run in

Cargo.lock, Cargo.toml, src/bin/typos-cli/args.rs, src/bin/typos-cli/main.rs, src/bin/typos-cli/report.rs, src/file.rs, src/policy.rs, src/report.rs
=> feat(cli): '--file-types' flag to help debug detection issues 

crates/typos-dict/assets/words.csv
Hi,
I propose to add this typo ('regylar' for 'regular') in the patch included. I'm not very used to git and not sure that this is the right process to submit a PR. Please tell me if I should do things differently.
Regards,
Olivier.
=> Adds 'regylar' as a typo for 'regular'.

CONTRIBUTING.md, crates/typos-dict/assets/words.csv
https://en.wiktionary.org/wiki/substituters
https://en.wiktionary.org/wiki/substituents
Example in the wild: https://nixos.org/manual/nix/unstable/command-ref/conf-file.html#conf-substituters
=> "substituters", "substituents"

README.md, src/bin/typos-cli/report.rs
Well, this was kind of ironic.
=> chore: typos

crates/typos-dict/assets/words.csv
| Typo       | Correction                                              |
| ---------- | ------------------------------------------------------- |
| detctable  | [detectable](https://en.wiktionary.org/wiki/detectable) |
| seaonal    | [seasonal](https://en.wiktionary.org/wiki/seasonal)     |
| wayferer   | [wayfarer](https://en.wiktionary.org/wiki/wayfarer)     |
=> feat: add detctable & seaonal & wayferer

crates/typos-dict/assets/words.csv
| Typo     | Correction                                           |
| -------- | ---------------------------------------------------- |
| someoene | [someone](https://en.wiktionary.org/wiki/someone)    |
=> feat: Add someoene

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Don't correct Referer

README.md
Fixes #666 
Just as the title says.
=> Edited README to show install instructions for `conda`

crates/typos-dict/assets/words.csv
- Add various new corrections that I ran into over last few months
=> Add additional corrections

crates/typos-dict/assets/words.csv
=> fix(dict): Allow commitish

Cargo.lock, crates/typos-cli/Cargo.toml, crates/typos-cli/src/file.rs
No idea if this will impact #641
Fixes #702
=> refactor: Switch out the UTF-16 encoding impl

crates/typos-dict/assets/words.csv
=> fix: Add April, 2023's typos

crates/typos-cli/tests/cmd/false-positives.in/README.md, crates/typos-cli/tests/cmd/false-positives.in/sample.py, crates/typos-cli/tests/cmd/false-positives.in/sample.rs, crates/typos-cli/tests/cmd/false-positives.toml, crates/typos-dict/assets/words.csv
=> fix(dict): Dont correct add-ons

action.yml, action/entrypoint.sh
This mirrors crate-ci/committed#339
Fixes #723
=> fix(action): Don't require sudo

Cargo.lock, crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Include May updates

crates/wikipedia-dict/assets/dictionary.txt
=> chore: remove trailing space from Wikipedia dictionary

crates/typos/src/tokens.rs
=> chore: remove usages of deprecated functions

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
Stop correcting the following valid words:
* simulative
* pervious
* perviously
* intension
* intensional
* intensionally
* unuseful
=> Allow some valid words

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Don't correct contiguities

crates/typos-dict/assets/words.csv
=> feat(dict): June updates

crates/typos-cli/src/file.rs
This isn't perfect as this only helps when doing checks and not in the parsing impls.
This supersedes #797
=> refactor(cli): Abstract away regex ignores

crates/typos-cli/src/file_type_specifics.rs
Followup PR for #793 (it will be rebased once that PR has been merged so that only the last three commits remain).
=>  fix(cli): Allow `Nd` in man, `nd` in css and `ot` & `stap` in sh

crates/typos-cli/src/bin/typos-cli/report.rs, crates/typos-cli/src/report.rs, crates/typos-cli/tests/cmd/config-disallowed.in/_typos.toml, crates/typos-cli/tests/cmd/config-disallowed.in/file, crates/typos-cli/tests/cmd/config-disallowed.toml
=> fix(cli): Report bad exit code on disallowed

crates/typos-cli/src/default_types.rs
=> fix: Dont check pnpm lockfiles

crates/typos-cli/src/bin/typos-cli/main.rs, crates/typos-cli/tests/cmd/missing-arg.toml
=> fix(cli): Improve error when args aren't present

crates/typos-dict/assets/words.csv
=> fix(dict): Treat arguement as a misspelling

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
A couple of the suggestions were actual words.
There was also a suggestion to replace a correction but both words seem valid, so I let them be merged.
Fixes #784
=> feat(dict): August updates

docs/reference.md
See https://github.com/crate-ci/typos/issues/361#issuecomment-1711720189
=> Document new `pyproject.toml` support

README.md
in response to https://github.com/crate-ci/typos/issues/263#issuecomment-1730995483
=> docs: add typos-lsp to README

crates/typos-cli/tests/cmd/ignore-line.in/_typos.toml, crates/typos-cli/tests/cmd/ignore-line.in/file.ignore, crates/typos-cli/tests/cmd/ignore-line.toml
Inspired by zulip/zulip-terminal#1429
=> test: Demo line-ignore behavior

crates/typos-cli/src/dict.rs, crates/typos-cli/tests/cmd/extend-words-case.in/_typos.toml, crates/typos-cli/tests/cmd/extend-words-case.in/file.txt, crates/typos-cli/tests/cmd/extend-words-case.toml
=> fix(dict): Mirror original case for custom dict

crates/typos-cli/src/file.rs, crates/typos-cli/tests/cmd/extend-ignore-re.in/_typos.toml, crates/typos-cli/tests/cmd/extend-ignore-re.in/olt-manager.php, crates/typos-cli/tests/cmd/extend-ignore-re.toml
=> fix(config): Apply extend-ignore-re to file names 

docs/github-action.md
Thanks for maintaining typos project. 
I'm using in [my project](https://github.com/kyu08/fzf-make)!
It helps me a lot! ❤️ 
I updated the document for GitHub Actions.
=> chore(docs): Bump actions/checkout to v4 in the GitHub Actions example

crates/typos-dict/assets/words.csv
=> feat(dict): November/December updates

.github/workflows/post-release.yml
`complete` directory is always empty.
=> Remove empty directory from release assets

crates/typos-dict/assets/words.csv
=> fix(dict): January updates

crates/typos-dict/assets/english.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Dont correct derivate

crates/typos-cli/tests/cmd/help.toml, crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): February updates

crates/typos-dict/assets/words.csv
=> fix(dict): March and other updates

crates/typos-dict/assets/english.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Remove Spile from being a typo

CHANGELOG.md
From https://github.com/crate-ci/typos/commit/31cbc32efffa9d1aef6d0fe2c80f5e1ed62ef8ba#commitcomment-140468950
=> Fix changelog for OpenGraph

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Always allow inout

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Don't correct kms

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Don't correct the doas command

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): April updates

crates/typos-dict/assets/words.csv
=> fix(dict): May updates

crates/typos-dict/assets/english.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Don't correct arbitral

crates/typos-dict/assets/words.csv
=> fix(dict): Improve spelling suggestions

crates/typos-dict/assets/english.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Don't correct reoccurrence

crates/typos-dict/assets/words.csv
=> fix(dict): June updates

crates/typos-cli/src/file_type_specifics.rs, crates/typos-cli/tests/cmd/false-positives.in/sample.cpp, crates/typos-cli/tests/cmd/false-positives.toml
=> fix(dict): Don't correct countr_one

crates/typos-cli/src/config.rs
=> feat(config): Load config from Cargo.toml

crates/typos-dict/assets/words.csv
=> fix(dict): July updates

crates/typos-cli/tests/cmd/en-us.in/README.md, crates/typos-cli/tests/cmd/en-us.in/_typos.toml, crates/typos-cli/tests/cmd/en-us.toml
We can't test much more until we have a way of dealing with `--no-default-features` in tests
=> test(cli): Verify locale false positives

crates/typos/src/tokens.rs
In some test data for rinja, they check some parsing corner cases. Unfortunately for us, also hit a performance corner case. The entire file was a valid email username but without an `@`. This mean for every byte, we checked that every byte after it was a valid username but then backtracked at the end, repeating this until the whole file was read.
Fixes #1088
=> perf(token): Don't allow unbounded backtrackable parsing

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Aug updates

crates/typos-dict/assets/words.csv
=> fix(dict): Sept updates

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv
=> fix(dict): Provisionally accept additionals

crates/typos-dict/assets/words.csv
=> feat(dict): Oct updates

crates/typos-dict/assets/words.csv, crates/typos-dict/tests/verify.rs
=> fix(dict): Prefer correcting alingment to alignment

crates/typos-dict/assets/words.csv
=> feat(dict): November updates

crates/typos-dict/assets/allowed.csv, crates/typos-dict/assets/words.csv, crates/typos-dict/tests/verify.rs
=> fix(dict): Don't correct parametrized 

Cargo.lock, crates/codespell-dict/Cargo.toml, crates/dictgen/Cargo.toml, crates/misspell-dict/Cargo.toml, crates/typos-cli/Cargo.toml, crates/typos-dict/Cargo.toml, crates/typos-vars/Cargo.toml, crates/typos/Cargo.toml, crates/wikipedia-dict/Cargo.toml
This removes some unused/dev-only deps around.
Local tests passed, lets see.
=> fix: remove some unused deps

crates/typos-cli/Cargo.toml, docs/github-action.md
- Linked with #1191
New readme https://github.com/Its-Just-Nans/typos/blob/update-doc/docs/github-action.md
=> Update doc for actions

Cargo.lock, crates/dictgen/Cargo.toml, crates/dictgen/src/insensitive.rs, crates/dictgen/src/lib.rs, crates/dictgen/src/map.rs, crates/dictgen/src/table.rs, crates/dictgen/src/trie.rs, crates/typos-dict/Cargo.toml
Somehow our PHF code path dropped PHF code gen and switched to Table codegen.  This adds it back and shows its faster than our trie.
=> fix(dictgen)!: Generate phf for map feature 

Cargo.lock, crates/typos-cli/Cargo.toml
=> chore(deps): Update compatible

.github/workflows/post-release.yml
=> chore(ci): maintain major tags for GitHub Actions

crates/typos-cli/src/default_types.rs
=> fix(type): Include support for go.work

crates/typos-dict/assets/words.csv, crates/typos-dict/benches/benches/aho_corasick_codegen.rs
This reduces problems from #1253 until a decision is made
=> fix(dict): Also correct typ to type

crates/typos-cli/src/bin/typos-cli/args.rs, crates/typos-cli/tests/cmd/help.toml
=> docs(cli): Clarify '-' behavior

crates/typos-dict/assets/words.csv, crates/typos-dict/tests/verify.rs
=> fix(dict): Remove blank corrections

crates/typos-dict/assets/words.csv
```diff
-diagnotics,diagnostic,diagnostics
+diagnotics,diagnostics
```
"diagnostic" feels like a much less likely correction than "diagnostics"
=> fix(dict): Remove correction to focus on nearest option

Cargo.lock, crates/typos-cli/Cargo.toml, crates/typos-cli/src/bin/typos-cli/args.rs, crates/typos-cli/src/config.rs, crates/typos-cli/tests/cmd/unknown-default-field.in/_typos.toml, crates/typos-cli/tests/cmd/unknown-default-field.toml, crates/typos-cli/tests/cmd/unknown-files-field.in/_typos.toml, crates/typos-cli/tests/cmd/unknown-files-field.toml, crates/typos-cli/tests/cmd/unknown-top-field.in/_typos.toml, crates/typos-cli/tests/cmd/unknown-top-field.toml, crates/typos-cli/tests/cmd/unknown-type-field.in/_typos.toml, crates/typos-cli/tests/cmd/unknown-type-field.toml
=> fix(config): Consistently error on unused key 
