crate-ci/typos

- benches/file.rs
- docs/about.md
- src/lib.rs
- src/main.rs
- src/tokens.rs
Trying to avoid accidentally correcting something that looks like a word
inside a hex number, like `0xBEAF`.
Fixes #19
>  feat(parser): Ignore hex literals

- src/main.rs
Don't give the user a false sense of hope.  It will be brought back in
as part of #7.
> fix: Remove threads flag

- docs/about.md
- src/lib.rs
- src/main.rs
> feat: Set exit code on typos being found

- typos/src/tokens.rs
Before
```
test process_code         ... bench:      25,627 ns/iter (+/- 2,062)
test process_corpus       ... bench:  20,192,253 ns/iter (+/- 603,029)
test process_empty        ... bench:       7,418 ns/iter (+/- 707)
test process_no_tokens    ... bench:       8,788 ns/iter (+/- 1,065)
test process_sherlock     ... bench:      30,420 ns/iter (+/- 2,699)
test process_single_token ... bench:       9,426 ns/iter (+/- 811)
test symbol_split_lowercase_long  ... bench:       2,763 ns/iter (+/- 246)
test symbol_split_lowercase_short ... bench:         110 ns/iter (+/- 12)
test symbol_split_mixed_long      ... bench:       7,373 ns/iter (+/- 1,111)
test symbol_split_mixed_short     ... bench:         357 ns/iter (+/- 86)
```
After
```
test process_code         ... bench:      20,973 ns/iter (+/- …
```
> perf: Speed up identifier splitting

- benches/file.rs
- src/config.rs
- src/main.rs
- typos/src/tokens.rs
Previously, you could specify whether identifiers included digits or not.  Now we distinguish between what is allowed in the first character of the identifier vs what can be included in the rest.  This let's us bypass hex/dec checks because they lead with a number which is now disallowed by default.
Micro-benchmarks showed no change to taking half the time.
>  perf: Use standard identifier rules to avoid doing umber checks 

- docs/reference.md
- src/config.rs
- src/main.rs
THis is to help with cases like a monorepo with vendored dependencies.
A user might want to search (`.ignore`) them but not hold the code to
the same standards as first-party code.
Fixes #134
> feat(ignore): Typos-specific ignores

- docs/reference.md
- src/config.rs
- src/dict.rs
- src/main.rs
Sometimes you just have to live with a typo or its done intentionally
(like weird company names).  With this commit, a user can now identifier
blessed identifiers and words.
This is ostly what is needed for #9 but sometimes people will have
common typos that they'll want to provide corrections for.
> feat(dict): Override builtin dictionary

- azure-pipelines.yml
- benches/corrections.rs
- crates/typos/src/checks.rs
- crates/typos/src/dict.rs
- crates/typos/src/report.rs
- crates/typos/src/tokens.rs
- docs/reference.md
- src/config.rs
- src/dict.rs
- src/main.rs
- src/replace.rs
Switching `valid-*` to just `*` where you map typo to correction, with
support for always-valid and never-valid.
Fixes #9
> feat: Custom dictionary support

- Cargo.lock
- Cargo.toml
- src/exit.rs
- src/main.rs
The main goal is to make spelling errors differentiated from other
errors.
Fixes #170
> fix(cli): Define an error code policy

- Cargo.lock
- Cargo.toml
- src/checks.rs
- src/main.rs
Now `ignore::Error` makes it convenient  to access its `std::io::Error`, let's just use that.
> fix: Return more precise errors

- Cargo.lock
- Cargo.toml
- docs/about.md
- src/checks.rs
We don't have good detection for non-UTF encodings and don't have
encoding support for UTF-32, so limiting it to just UTF-16.
Fixes #17
> feat: Check and replace UTF-16 files

- .clog.toml
- CHANGELOG.md
- LICENSE-MIT
At some point early on, this project was renamed from "scorrect" to
"typos". Some references to old URLs still exist. This commit corrects
those references.
Unrelatedly, I'm facing an issue building typos as one of the dependencies, `derive_setters`, fails to build after an update (v1.0.58) to its own dependency, `syn` changed its public API: https://github.com/Lymia/derive_setters/pull/3
I attempted to raise an issue or revert PR with https://github.com/dtolnay/syn, as this is a breaking change in a point-release, but the project does not allow non-contributors to create issues or pull requests.
I then attempted to pin `syn` to "1.0.57" in this project's Cargo.toml, however it seems this does not affect what dependency version is selected for sub-dependencies (please, correct me if I'm …
> Replace instances of scorrect with typos

- Cargo.lock
- Cargo.toml
See https://users.rust-lang.org/t/syn-1-0-58-breaks-test-case-and-parameterized/53823/4
Can be removed after https://github.com/Lymia/derive_setters/pull/3 is merged and released.
> fix: Force a specific 'syn' version

- docs/reference.md
- src/args.rs
- src/config.rs
- src/main.rs
- src/policy.rs
This includes a `--type-list` to know what types are available.  This does not yet include support for adding custom types or error reporting if a non-existent type is referenced.
> feat(config): Per-file type settings 

- crates/typos/src/tokens.rs
- src/dict.rs
`Scream` was referrin to `SCREAMING_CASE` but outside of that context, I
think `Upper` is more accurate.
> fix(typos)!: Clarify `Case::Upper`s name

- Cargo.lock
- benches/tokenize.rs
- crates/typos/Cargo.toml
- crates/typos/src/tokens.rs
- docs/reference.md
- src/args.rs
- src/config.rs
- src/policy.rs
From the user-facing perspective, we are deferring to the Unicode XID spec for the definition of an identifier, rather than having the user specify it.  We are also offering an ASCII fast path via `--no-unicode` / `default.unicode = false`.
Internally, we are switching from `regex` to `nom` for parsing.  I'm hoping this will give us some more flexibility in the parser, like email detection if we want it.
Before
```
parse_str/unicode/empty
time:   [32.826 ns 33.207 ns 33.590 ns]
parse_str/unicode/no_tokens
time:   [58.848 ns 59.315 ns 59.890 ns]
parse_str/unicode/single_token
time:   [95.329 ns 95.700 ns 96.133 ns]
parse_str/unicode/sherlock
time:   [5.1198 us 5.2072 us 5.3122 us]
parse_str/unicode/code
time:   [3.4724 us 3.5158 us 3.5681 us]
parse_str/unicode/corpus
time:   [4.4684 ms …
```
> perf(parser): Overhaul how parsing is done

- crates/typos-dict/codegen/src/main.rs
- crates/typos-dict/src/dict_codegen.rs
- crates/typos-vars/codegen/src/main.rs
- src/dict.rs
The code was generated with separate min / max, rather than using a
Range and ensuring the API is used correctly.
> fix(dict)!: Clarify word sizes with Ranges

- src/file.rs
- src/lib.rs
For now, I'm just punting on `typos_cli`s API.
Fixes #171
> fix(cli): Clarify API stabiliy

- src/config.rs
- src/policy.rs
My only guess is that in a76ddd4, I lost track of different parts of my
change and never re-implemented this logic.
> fix(cli): Discover config in parent dirs 

- src/bin/typos-cli/main.rs
- src/file.rs
- src/policy.rs
Before, we always displayed absolute paths and now we'll display
relative ones.
The main issue was loading the config correctly.  We just have to
cannonicalize whenever doing so.
> fix(cli): Display shortened paths to users

- crates/typos-vars/codegen/src/main.rs
- src/dict.rs
Variant support slows us down by 10-50$.  I assume most people will run
with `en` and so most of this overhead is to waste.  So instead of
merging vars with dict, let's instead get a quick win by just skipping
vars when we don't need to.  If the assumptions behind this change over
time or if there is need for speeding up a specific locale, we can
re-address this.
Before:
```
check_file/Typos/code   time:   [35.860 us 36.021 us 36.187 us]
thrpt:  [8.0117 MiB/s 8.0486 MiB/s 8.0846 MiB/s]
check_file/Typos/corpus time:   [26.966 ms 27.215 ms 27.521 ms]
thrpt:  [21.127 MiB/s 21.365 MiB/s 21.562 MiB/s]
```
After:
```
check_file/Typos/code   time:   [33.837 us 33.928 us 34.031 us]
thrpt:  [8.5191 MiB/s 8.5452 MiB/s 8.5680 MiB/s]
check_file/Typos/corpus time:   [17.521 ms 17.620 ms 17.730 ms] …
```
> perf(dict): Bypass vars when possible

- docs/reference.md
- src/bin/typos-cli/args.rs
- src/bin/typos-cli/main.rs
- src/config.rs
We want both CLI and config ignores.  The question then is what we make
them relative to.  I decided to favor CLI with `.`.  We'll see how this
works out
Fixes #134
> feat(ignore): Typos=specific ignores

- CHANGELOG.md
- src/file.rs
I didn't count on how `buffer.lines().count()` would handle different
corner cases, like slices with no `\n`, slices with trailing `\n`, etc.
Fixes #259
> fix: Count lines correctly

- CHANGELOG.md
- src/bin/typos-cli/report.rs
- src/file.rs
When rendering typos, we look up what visual column the typoe starts on
but I mixed a raw byte offset with the offset into a lossy string.  This
caused panics when dealing with non-ascii content.
Fixes #258
> fix(cli): Don't panic when finding column

- .github/workflows/test-action.yml
- Cargo.toml
- Dockerfile
- README.md
- action.yml
- docker/Dockerfile
- docker/entrypoint.sh
- docs/github-action.md
Hi @epage!
I really love this little tool, and wanted an easy way to add it to CI for some of my repos to check my spelling. I thought it might be useful to have a GitHub action, so this pull request is adding one here! The user will be able to add a step to a GitHub Workflow that looks like:
```yaml
- name: Test extend identifiers
uses: crate-ci/typos@<branch, commit, or relase>
with: 
files: ./file.txt
force_pass: false
extend_words: "word1,word2"
extend_identifiers: "IdentifierToAdd,Secondidentifier"
```
And spell check some portion of their repository.  I've added a documentation page, and a GitHub Workflow to both demonstrate usage and test the action. Some points for discussion!
1. If you absolutely don't want it served alongside the code here, I'd be happy to put in its own …
> Adding github action to use typos to check spelling

- docs/github-action.md
The repository of crate-ci/typos does not have a "main" branch, "master" is used instead.
> Fix example in github-action.md

- Cargo.lock
- benches/corrections.rs
- crates/typos-vars/Cargo.toml
- crates/typos-vars/codegen/Cargo.toml
- crates/typos-vars/codegen/src/main.rs
- crates/typos-vars/src/lib.rs
- src/dict.rs
This dropped RSS (memory usage) from 4GB to 1.5GB when compiling.
This could impact performance (phf to binary search, adding an extra match) but not too concerned since
the default is to not look within vars.
> refactor(varcon): Remove reliance on const-fn 

- CHANGELOG.md
- src/bin/typos-cli/report.rs
I misused `compare_exchange` when I didn't even really need it.
Fixes #284
> fix(cli): Don't crash on races

- .pre-commit-hooks.yaml
- Cargo.toml
- docs/pre-commit.md
- setup.py
For no additional build dependencies (besides Python >= 3.6), and faster
install.
The setup.py here is a copy of the one at
https://github.com/shellcheck-py/shellcheck-py with changes kept at the
bare minimum for future diffability.
We don't support checksumming at least yet, because there's no access to
them from cargo-release at the moment.
Closes #285
> feat(pre-commit): add binary based install

- CHANGELOG.md
- crates/typos/src/tokens.rs
- docs/comparison.md
- docs/reference.md
- src/policy.rs
We need to balance
- false positives
- false negatives
- performance
These seem like a reasonable blend of cases to detect and ignore without ignoring much, if any,  code.
> Detect non-identifiers to ignore

- crates/typos/src/tokens.rs
In #293, we moved where we were filtering out results but never
switched from `filter_map` to map`, so this does that.
> refactor(typos): Remove unused calculations

- CHANGELOG.md
- crates/typos/src/tokens.rs
Since our goal is 100% confidence in the results, its better to not
check words than to correct the wrong words.
With that in mind, we'll ignore words after what might be c-escape
sequences (`\nfoo`) or printf substitutions (`%dfoo`).
Fixes #3
> fix(parser): Handle c-escape/printf

- crates/typos/src/tokens.rs
By experimentation (see ticket), it seems that same-case hexadecimal
strings of 32 characters or longer are almost never intended to hold
text.  By treating such strings as ignored, we can resist a larger
category of false positives.
Closes #326.
> Ignore hexadecimal "hashes" of length 32 or greater.

- Cargo.lock
- Cargo.toml
- crates/typos/src/tokens.rs
- tests/cmd/double-escaped.stdin
- tests/cmd/double-escaped.stdout
- tests/cmd/double-escaped.toml
If escape sequences follow straight after each other, there is no
delimiter in-between.
In such a case, parsing previously stopped and did not find any
typos further in the file.
Also change the c-escape parser to take either \\+\<single char> or
\\+\<char sequence delimited by space or similar>.
Also update trycmd, so failures actually show up in CI.
> Fix multiple escape sequences

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/typos-cli/main.rs
- src/config.rs
We could generate the config with `--dump-config` but could not read it because of problems with serde.
> fix(config): Ensure type-specific settings work

- .dockerignore
- Cargo.toml
- Dockerfile
Builds all the binaries on demand, then creates a new image with just the binary.
Easy to do tagged releases or multi arch builds, etc.
> New dockerfile for #427.

- docs/reference.md
Escape left angle bracket, fix copy-pastos in default.extend-identifiers and default.extend-words descriptions.
> docs(reference): Formatting and copy-pasto fixes

- crates/typos/src/tokens.rs
Microsoft toolchains usually emit UUID/GUID in UPPERCASE
> Fix tokenizer for uppercase UUID

- Cargo.lock
- Cargo.toml
- src/bin/typos-cli/report.rs
- tests/cmd/stdin-failure-multiwidth.stdin
- tests/cmd/stdin-failure-multiwidth.stdout
- tests/cmd/stdin-failure-multiwidth.toml
Previous method misaligns highlights when there are double width asian characters
```
39 |  한글 eglish
|    ^^^^^^
```
This commit fixes the highlight to have correct alignment.
```
39 |  한글 eglish
|      ^^^^^^
```
`unicode-rs` crate is used by the Rust compiler [1].
[1]: https://github.com/rust-lang/rust/blob/34a6c9f26e2ce32cad0d71f5e342365b09f4d12c/compiler/rustc_errors/src/emitter.rs#L861
I've intentionally left `column` variable as is since many IDE counts by grapheme clusters.
> Fix misalignment in report highlight and indent when there are double width characters

- crates/typos/src/tokens.rs
> fix(parser): Improve detection of ignorable cases

- crates/varcon-core/src/lib.rs
- src/dict.rs
- src/policy.rs
This is in part to help in cases like https://github.com/crate-ci/typos/issues/487 but it will also help people
generally configure and debug their config.
> feat(cli): Log the policy

- Cargo.lock
- Cargo.toml
- src/bin/typos-cli/main.rs
- src/file_type.rs
- src/lib.rs
- src/policy.rs
Before, when two file types matched the same glob, the file type that
one was non-deterministic.
Now, "the more specific" file type wins.  What this means is that we
break up the file by its extensions and prioritize the more literal glob
- If its just `*`, then its lowest priority
- If it contains `*` and other logic, then its next
- If it doesn't contain a `*`, then its the highest priority
This leaves out other glob syntax like `{one,two}` as those are
closed-ended and so considered specific still.
Fixes #487
> fix(config): Resolve ambiguous file types

- crates/typos-dict/assets/words.csv
I can't find any references to "opauqe" as an actual word, so I believe
this to be safe.
Thanks for this library!
> Correct "opauqe" to "opaque"

- crates/typos/src/tokens.rs
> fix(parse): Ignore CSS hex values that start with digits

- crates/typos-dict/assets/words.csv
baged -> bagged
baged -> badge
codesbase -> codebase (+ variants)
depercate -> deprecate (+ variants)
fallthough -> fallthrough
> feat(dict): Add assorted typos

- Dockerfile
Make `typos` the `ENTRYPOINT` rather than cmd, and output `--help` by default.
Provides for better UX when running the image without arguments, and facilitates just passing args to `typos` instead of having to repeat the command name.
BREAKING CHANGE: `typos` must no longer given as the first argument when running the Docker image, as it is the default `ENTRYPOINT` now.
> feat: Improve Docker image entry

- .pre-commit-hooks.yaml
- docs/pre-commit.md
Mostly as an alternative to the src install, but trading host dependency on Rust with one on Docker.
> feat: Add Docker pre-commit hook

- CONTRIBUTING.md
* This repository doesn't use travis. So changed the link to `.github/workflows`.
* An external link without a scheme doesn't work well. So added a scheme to the link.
> docs: Fix broken links in contribution doc

- action.yml
- docker/entrypoint.sh
- docs/github-action.md
Hi! I think it'd make sense to allow writing changes in the github action itself, so that this can be combined with other actions like https://github.com/getsentry/action-git-diff-suggestions. That way, I can run `typos` in my repository, and instead of a hard failure, it will suggest code changes to fix the typos.
See https://github.com/bnjbvr/octotest/pull/5 for an example.
(The entrypoint file will run the command twice, so I suspect that it will only have an effect the first time. I can tweak the script so it doesn't, but as far as I could tell, this didn't add extra warnings or other issues, so that seemed ok to me. Let me know if you'd like me to fix that!)
> Allow writing changes in the github action

- crates/typos-dict/assets/words.csv
Simple addition of a new typo to the dictionary. `grouepd -> grouped`.
> Added `grouepd` to the typos dictionary

- setup.py
Fixes #682. 
Can be tested by adding the following to your pre-commit config.
```
- repo: https://github.com/calumy/typos
rev: ec6998b
hooks:
- id: typos
```
I have tested this locally, and it appears to work.
> fix(pre-commit): Update package_dir

- crates/typos-cli/src/default_types.rs
> fix: ignore go.mod by default

- crates/typos-dict/assets/words.csv
`existend` can not also be `existed` but also  `existent`.
> change(dict): existend => existed,existent

- crates/typos-dict/assets/words.csv
This adds a typo variant that I found in the code base of the [uefi](https://github.com/rust-osdev/uefi-rs) crate.
> feat(dict): Add: erronerous -> erroneous

- Cargo.lock
- crates/typos-cli/Cargo.toml
- crates/typos-cli/src/bin/typos-cli/main.rs
- crates/typos-cli/src/bin/typos-cli/report.rs
- `CLICOLOR=1` now works correctly
- `NO_COLOR=` now works correctly
- Auto-enable colors in CI
For running `typos` on the Linux kernel (176,210 typos to be printed), we went from 20.082s to <20.450s.  Where in that range is unclear due to jitter in my system.
```console
$ hyperfine -L typos ./typos-main,./typos-anstream "{typos} ../../../linux" -i
Benchmark 1: ./typos-main ../../../linux
Time (mean ± σ):     20.082 s ±  0.111 s    [User: 39.668 s, System: 0.474 s]
Range (min … max):   19.961 s … 20.331 s    10 runs
Warning: Ignoring non-zero exit code.
Benchmark 2: ./typos-anstream ../../../linux
Time (mean ± σ):     20.426 s ±  0.104 s    [User: 40.301 s, System: 0.523 s]
Range (min … max):   20.316 s … 20.661 s    10 runs
Warning: Ignoring non-zero exit code.
Summary
'./typos-main …
```
> fix: Improve color env variable support

- crates/typos-cli/src/bin/typos-cli/args.rs
- crates/typos-cli/src/config.rs
- crates/typos-cli/src/file.rs
- crates/typos-cli/src/policy.rs
- crates/typos-cli/tests/cmd/extend-ignore-re.in/_typos.toml
- crates/typos-cli/tests/cmd/extend-ignore-re.in/file.ignore
- crates/typos-cli/tests/cmd/extend-ignore-re.toml
- crates/typos/src/check.rs
- crates/typos/src/tokens.rs
- docs/reference.md
Typos primarily works off of identifiers and words.  We have built-in
support to detect constructs that span identifiers that should not be
spell checked, like UUIDs, emails, domains, etc.  This opens it up for
for user-defined identifier-spanning constructs using regexes via
`extend-ignore-re`.
This works differently than any of the previous ways of ignoring thing
because the regexes require extra parse passes.  Under the assumption
that (1) actual typos are rare and (2) number of files relying on
`extend-ignore-re` are rare, we only do these extra parse passes when a
typo is found, causing almost no performance hit in the expected case.
While this could be used for more generic types of ignores, it isn't the
most maintainable because it is separate from the source files in
question. …
> feat(config): Custom ignores

- crates/typos-cli/src/file.rs
Two problems
- I thought we had a UTF-16 test but apparently we didn't
- I didn't read enough fine print in the `encoding_rs` API
These combined meant the last release completely broke UTF-16 support.
> fix(cli): Actually decode UTF-16

- action/entrypoint.sh
Because the action runs without a tty, `wget` defaults to `--progress dot`.  This prints a dot per 1K of data.  Due to the size of `typos`, switching to `--progress dot:mega` is better as it only prints one dot per 64K.
```
0K ........ ........ ........ ........ ........ ........ 51% 11.7M 0s
3072K ........ ........ ........ ........ ........ .....   100% 12.0M=0.5s
```
> fix(action) Make wget progress indicator much smaller

- crates/typos-dict/assets/allowed.csv
- crates/typos-dict/assets/words.csv
"accreting" is the present participle of "accrete", see https://en.wiktionary.org/wiki/accreting. Don't correct it to "accrediting".
> fix(dict): Don't correct "accreting"

- crates/typos-cli/src/bin/typos-cli/report.rs
In 3a29410c1b31186692cf1079174499ddaa26bd52, we switched to anstream which doesn't seem to be locking properly (rust-lang/cargo#12289).  For now, we are working around it.
Fixes #749
> fix: Ensure stdout is locked

- crates/typos-cli/src/config.rs
- crates/typos-cli/src/file.rs
- crates/typos-cli/tests/cmd/extend-builtin-dict.in/_typos.toml
- crates/typos-cli/tests/cmd/extend-ignore-identifiers-re.in/_typos.toml
- crates/typos-cli/tests/cmd/extend-ignore-re.in/_typos.toml
- crates/typos-cli/tests/cmd/override-default-type.in/_typos.toml
This doesn't use `extend-exclude` which means that `typos typos.toml` will stil be skipped
This doesn't just skip the currently loaded config but any file name that looks like a config, which might be a big aggressive but allows us to do layered config in the future....  We've been saying that for a while.
Fixes #711
> fix(config): Force-skip config files

- crates/typos-dict/assets/allowed.csv
- crates/typos-dict/assets/words.csv
> fix(dict): Dont correct currency code

- crates/typos-dict/tests/verify.rs
> Refactor generate and add tests

- Cargo.lock
- crates/typos-cli/Cargo.toml
- crates/typos-cli/src/config.rs
- crates/typos-cli/src/file_type_specifics.rs
- crates/typos-cli/src/lib.rs
> refactor(cli): Introduce file_type_specifics module

- crates/typos-cli/Cargo.toml
- crates/typos-cli/pyproject.toml
PyO3/maturin-action says
> ⚠️ Warning: specify [package.metadata.maturin] name in Cargo.toml is deprecated, use module-name in [tool.maturin] section in pyproject.toml instead
> chore: move deprecated package.metadata.maturin

- crates/typos-cli/src/config.rs
- crates/typos-cli/src/file.rs
- crates/typos-cli/tests/cmd/missing-config.toml
Trying to improve things for #806
> fix(cli): Add path to filesystem errors

- action/entrypoint.sh
This reverts commit fc7f51746699c0dacd6a3c2a8f594a18c1726336.
This has two problems
- This doesn't correctly handle spaces, likely needing #708
- This overrides excludes, see #347
This also has a weird cost/benefit balance because this requires enough repo history to do the analysis which takes time to pull down.
Rather than waiting until the relevant changes are in to make this work, I'm pulling this out for now.
Fixes #806
> fix(action): Don't pre-filter checked files

- crates/typos-cli/src/config.rs
This PR adds support for parsing `pyproject.toml` config files. The convention for these files is to put any tooling related configuration into the `tool.NAME` section, so in this case, `tool.typos`. I have verified that the changes are pulled correctly even if the `tool.typos` section is not present.
Closes #361.
PS: I am new to Rust, so let me know if there are any improvements that can be made! I'm new to Serde as well, so I'm unfamiliar with what options do/don't need to be there (I just copied the traits on the `Config` struct).
> Add support for `pyproject.toml` files

- Cargo.lock
Runs `cargo upgrade`, and allows the project to be built in the latest nightly version (downstream procmacro2 dependency).
> chore: Enable building on nightly

- .github/workflows/post-release.yml
> chore(ci): Add aarch64 support

- crates/typos-cli/src/default_types.rs
- crates/typos-cli/src/file_type_specifics.rs
> fix(config): Don't treat ts as typoscript 

- README.md
Hello
While reading through the README, I noticed a small typo where "identifier" was mistakenly written as "identifer". So, I went ahead and created a PR to fix it.
> Fix Typo in README: "identifer" to "identifier"

- crates/typos-dict/assets/allowed.csv
- crates/typos-dict/assets/words.csv
> fix(dict): Don't correct OpenGraph's namespace

- crates/typos-dict/assets/allowed.csv
- crates/typos-dict/assets/words.csv
Listed in #955, but `JST` is used as time zone context
https://data.iana.org/time-zones/theory.html
https://github.com/eggert/tz/blob/b1e07fb0779a8075c7f9d862c784dfbd31965c1a/theory.html#L463
> fix(dict): Don't correct JST used in time zone abbreviations

- crates/typos-dict/assets/words.csv
Fixes #968
After this change
```console
> echo "/// If true, the screenshotter was told at startup to quit after it's donw." | ./target/debug/typos -
error: `donw` should be `down`, `done`
--> -:1:71
|
1 | /// If true, the screenshotter was told at startup to quit after it's donw.
|                                                                       ^^^^
|
```
---
[Above listed typo `donn`](https://github.com/crate-ci/typos/pull/972/files#diff-d7206c435daafa1b53ca9227408de1a1b8c199cb61b5a21973add69b14afd5caL20607) is not related to down, but that is not issued in this 9 months. So I didn't update the `donn` in this PR.
> feat(dict): Add suggestion "done" for the typo "donw"

- crates/typos-cli/src/file_type_specifics.rs
> fix: Don't correct common Python identifiers

- crates/typos-dict/assets/allowed.csv
- crates/typos-dict/assets/words.csv
Common abbreviation for High Definition
Fixes #987
> Don't correct `HD`

- crates/typos-cli/src/default_types.rs
Add more python file extensions. Namely `.ipynb` for jupyter notebook files, and `.pyi` for stub files.
> Add more python file extensions

- crates/typos-cli/src/dict.rs
- crates/typos-cli/tests/cmd/false-positives.in/sample.txt
- crates/typos-cli/tests/cmd/false-positives.toml
I went with the direct unit which will be considered and identifier by
the casing, rather than also allowing this as a word.
Fixes #997
> fix(dict): Don't correct dBA

- crates/typos-cli/tests/cmd/ignore-block.in/_typos.toml
- crates/typos-cli/tests/cmd/ignore-block.in/file.ignore
- crates/typos-cli/tests/cmd/ignore-block.toml
- docs/reference.md
Needed a `(?s)` to match multiple enclosed newlines. And added a non-greedy modifier and matching test to prevent double blocks from causing intermediate lines to be ignored:
```shell
should be ignored
should not be ignored  # without non-greedy, this is also ignored
should be ignored
```
And tweak the examples to support both `#` and `//` comment leaders.
> docs(ref): Add dotall specifier to block ignore

- crates/typos-cli/src/file_type_specifics.rs
`flate` is part of the standard library.
> fix(dict): ignore flate for Go files

- docs/github-action.md
Very minor, but I noticed a few trailing spaces when copy-pasting the GitHub action.
> Fix trailing spaces

- .github/workflows/post-release.yml
we (`jenkins infra team`) would like to use an ARM64 linux version of typos. 
Reading this issue https://github.com/crate-ci/typos/issues/828 and this PR https://github.com/crate-ci/typos/pull/908 it sounds like it was just missing a build block for linux arm64 ... seem a little too easy but I did this at least to make my contribution to the task.
> feat(release): Add linux arm64 build to matrix

- .github/workflows/test-action.yml
- action/entrypoint.sh
I've tested this on an M1 mac to make sure it works.
> add support for mac and arm systems to the github action

- crates/typos-dict/assets/words.csv
Some from #1024 that were missed in #1052
> fix(dict): Add more june typos

- Cargo.lock
- crates/typos/Cargo.toml
- crates/typos/src/tokens.rs
> feat(tokens): Ignore JWTs 

- Dockerfile
The Dockerfile might have been old (from before the project was a workspace) and the path to the installable crate was wrong. 
This also broke the pre-commit docker hook, which was important for me since I couldn't get the default one to work on NixOS.
> fix the crate install path in Dockerfile

- crates/typos-cli/src/bin/typos-cli/report.rs
- crates/typos-cli/src/file.rs
- crates/typos-cli/src/policy.rs
- crates/typos-cli/src/report.rs
Fixup for https://github.com/crate-ci/typos/pull/1077 , and a few other syntax modernisation.
> Fix BinaryFile display

- crates/typos-cli/src/policy.rs
This was broken in #882
Skipped tests because `locale` support is behind a default feature and we don't support features yet with our end-to-end tests
> fix(config): Don't overwrite locale and tokenizer config 

- crates/typos-dict/assets/words.csv
Sorry, I might have written a [wrongly formatted request](https://github.com/crate-ci/typos/issues/1069#issuecomment-2271530487) for multiple candidates. 
```plaintext
grather -> greater|gather
```
Typos now detect it as a disallowed word. I don't have confidence that this is valid or invalid because this pattern is not found for other entries.
Current
---
```console
> cargo test --workspace --no-run
> echo 'grather' | ./target/debug/typos --version -
typos-cli 1.24.3
> echo 'grather' | ./target/debug/typos -
error: `grather` is disallowed
--> -:1:1
|
1 | grather
| ^^^^^^^
|
```
After this change
---
```console
> echo 'grather' | ./target/debug/typos -
error: `grather` should be `greater`, `gather`
--> -:1:1
|
1 | grather
| ^^^^^^^
|
```
> fix(dict): Add suggestions "greater" and "gather" for the typo "grather"

- .github/workflows/test-action.yml
- action/entrypoint.sh
This PR contains changes to the GitHub Actions workflow to add support for Windows with Cygwin, MSYS2, and MinGW.
Related tests have been added to ensure that the changes work as expected. Currently it is necessary to manually install wget for Github Actions' Windows runner to work with typos.
> feat(action): Add Windows support to actions

- crates/typos-cli/src/bin/typos-cli/main.rs
- crates/typos-cli/src/file.rs
- crates/typos-cli/tests/cmd/force-exclude.in/binary
- crates/typos-cli/tests/cmd/force-exclude.toml
> fix(cli): Respect force-exclude for binary files 

- crates/typos-dict/assets/allowed.csv
- crates/typos-dict/assets/words.csv
> fix(dict): Accept tesselate variant

- crates/typos-dict/tests/verify.rs
This mirrors 17b4d0267eab0b23ff9c704ca0fcf1f2de7ea036
> test(dict): Don't use unverified varcon

- crates/typos-dict/assets/words.csv
Title says it all :) Accidentally typed "fand" instead of "find" today and there wasn't a rule to catch it.
> Add "fand" corrections to the dictionary

- crates/typos-dict/assets/allowed.csv
- crates/typos-dict/assets/words.csv
> fix(dict): Recognize alloced and requestor

- docs/reference.md
I hope I got the defaults right.
> docs(ref): Document config defaults

- crates/typos-cli/src/default_types.rs
This adds dtso (device tree source overlay) as a recognized devicetree type.
> feat: Recognize dtso as devicetree type

- Cargo.lock
- crates/typos-cli/Cargo.toml
- crates/typos-cli/src/bin/typos-cli/args.rs
- crates/typos-cli/src/bin/typos-cli/main.rs
- crates/typos-cli/src/bin/typos-cli/report.rs
- crates/typos-cli/src/report.rs
- crates/typos-cli/tests/cmd/help.toml
- crates/typos-cli/tests/cmd/sarif.in/_typos.toml
- crates/typos-cli/tests/cmd/sarif.in/bad
- crates/typos-cli/tests/cmd/sarif.in/good
- crates/typos-cli/tests/cmd/sarif.toml
- deny.toml
Closes: #594 
I asked earlier if anyone had already worked on this feature and got no reply https://github.com/crate-ci/typos/issues/594#issuecomment-2179277793 , so I added this implementation myself.
But as I declared, I'm not a professional rust developer, so this patch obviously contains a lot of problems caused by a lack of understanding of rust, such as `.unwrap` abuse, since I'm not sure how to properly convert `Error` to `io::Error`.
I enabled `Allow edits by maintainers`, so if you have any suggestions for syntax changes, please push them directly to the corresponding repository branch, thanks!
> feat: implement sarif format reporter

- docs/reference.md
Config Fields is quite a section, and if you want to make a reference directly to the very helpful extend-ignore-re examples today you can't.
> docs: add linkable header to example configurations

- crates/typos/src/tokens.rs
> Fix a typo in tokens.rs

- crates/typos-cli/src/bin/typos-cli/args.rs
- crates/typos-cli/src/bin/typos-cli/main.rs
- crates/typos-cli/src/file.rs
- crates/typos-cli/tests/cmd/help.toml
This makes it easier to evaluate word splitting
Fixes #1254
> feat(cli): Add '--highlight-<identifiers|words>' flags

- crates/typos/src/tokens.rs
> fix(token): Improve email detection by prefering that over base64 

- crates/typos-cli/src/file_type_specifics.rs
Closes #1055 
Does not address markdown files, but I would argue that is a separate issue.
> fix: ignore `ratatui` in Rust files

- crates/typos-cli/pyproject.toml
> feat: Add more metadata about the project for PyPi

- Cargo.lock
- crates/typos-cli/Cargo.toml
- crates/typos-cli/src/bin/typos-cli/report.rs
- crates/typos-cli/tests/cmd/config-disallowed.toml
- crates/typos-cli/tests/cmd/extend-exclude-inverted.toml
- crates/typos-cli/tests/cmd/extend-ignore-identifiers-re.toml
- crates/typos-cli/tests/cmd/extend-ignore-re.toml
- crates/typos-cli/tests/cmd/extend-ignore-words-re.toml
- crates/typos-cli/tests/cmd/extend-words-case.toml
- crates/typos-cli/tests/cmd/file-list-stdin.toml
- crates/typos-cli/tests/cmd/filename-typo.in/README.md
- crates/typos-cli/tests/cmd/filename-typo.toml
- crates/typos-cli/tests/cmd/ignore-block.toml
- crates/typos-cli/tests/cmd/ignore-line.toml
- crates/typos-cli/tests/cmd/ignore-next-line.toml
- crates/typos-cli/tests/cmd/stdin-failure-multiwidth.toml
- crates/typos-cli/tests/cmd/stdin-failure.toml
This is rustc/cargo's renderer and has all of the lessons of those,
including
- Unicode support
- Line wrapping / eliding of text to fit on screen
As part of this, we are now rendering file name typos like file
content typos.
This is a bit sloppy when it comes to terminal and unicode detection as it doesn't actually check the stream we are writing to.
This changed what we render the column number as when there are multi-byte characters present
Using `Patch`s for corrections is blocked on rust-lang/annotate-snippets-rs#300
> fix(cli): Replace error renderer with annotate-snippets 

- crates/typos-cli/src/file_type_specifics.rs
Here are some stats about the usage of these method/types
- [cipher.NewCBCEncrypter](https://github.com/search?q=language%3Ago%20%2Fcipher%5C.NewCBCEncrypter%2F%20-is%3Afork&type=code)
- [cipher.NewCFBEncrypter](https://github.com/search?q=language%3Ago%20%2Fcipher%5C.NewCFBEncrypter%2F%20-is%3Afork&type=code)
- [elf.Rela32 and elf.Rela64](https://github.com/search?q=language%3Ago%20%2Felf%5C.Rela(32%7C64)%2F%20-is%3Afork&type=code)
- [os.O_WRONLY or syscall.O_WRONLY](https://github.com/search?q=language%3Ago%20%2F(os|syscall)%5C.O_WRONLY%2F%20-is%3Afork&type=code)
- [syscall.NOTE_FFOR](https://github.com/search?q=language%3Ago%20%2Fsyscall%5C.NOTE_FFOR%2F%20-is%3Afork&type=code)
https://pkg.go.dev/debug/elf#Rela32
https://pkg.go.dev/debug/elf#Rela64 …
> fix(dict): add Go exclusions
